#Autograd

PyTorch makes **differentiation** (computing gradients) easy and efficient by providing the **autograd** package. This allows you to automatically compute the gradients of tensors during backpropagation, which is essential for training machine learning models, particularly in deep learning.


When you perform operations on tensors that have requires_grad=True, PyTorch builds a computation graph under the hood. When you call .backward(), it:

Traverses the graph

Applies the chain rule

Computes gradients automatically

In [1]:
import torch

# Create a tensor with gradient tracking enabled
x = torch.tensor(2.0, requires_grad=True)

# Some operation
y = x ** 3    # y = x^3 = 8

# Backward pass
y.backward()

# Check gradient (dy/dx = 3x^2 = 3*4 = 12)
print(x.grad)   # tensor(12.)


tensor(12.)


#Functionality of Autograd

x.requires_grad=True tells PyTorch to track operations on x

y = x**3 creates a computation graph

y.backward() computes the gradient of y with respect to x

x.grad gives you the result: 12

## DataLoader and Dataset

#Dataset

Think of Dataset as a wrapper around your data. It helps PyTorch know:

What your inputs and targets are

How many samples you have

How to retrieve each sample

It's a class where you define how your dataset looks and how to access it.

How to Use:

You create a custom dataset by subclassing torch.utils.data.Dataset and implementing:

__len__() → returns number of samples

__getitem__(idx) → returns one data sample at index idx

#DataLoader


Once you have a dataset, DataLoader helps you:

Batch your data (e.g., 32 samples at a time)

Shuffle it during training

Use multiple workers to speed up data loading

In [19]:
from torchvision.datasets import MNIST
from torchvision import transforms

dataset = MNIST(root='data/', train=True, transform=transforms.ToTensor(), download=True)
loader = DataLoader(dataset, batch_size=64, shuffle=True)


100%|██████████| 9.91M/9.91M [00:00<00:00, 16.0MB/s]
100%|██████████| 28.9k/28.9k [00:00<00:00, 477kB/s]
100%|██████████| 1.65M/1.65M [00:00<00:00, 4.45MB/s]
100%|██████████| 4.54k/4.54k [00:00<00:00, 7.01MB/s]


In [2]:
from sklearn.datasets import make_classification
import torch

In [3]:
# Step 1: Create a synthetic classification dataset using sklearn
X, y = make_classification(
    n_samples=10,       # Number of samples
    n_features=2,       # Number of features
    n_informative=2,    # Number of informative features
    n_redundant=0,      # Number of redundant features
    n_classes=2,        # Number of classes
    random_state=42     # For reproducibility
)

In [4]:
X

array([[ 1.06833894, -0.97007347],
       [-1.14021544, -0.83879234],
       [-2.8953973 ,  1.97686236],
       [-0.72063436, -0.96059253],
       [-1.96287438, -0.99225135],
       [-0.9382051 , -0.54304815],
       [ 1.72725924, -1.18582677],
       [ 1.77736657,  1.51157598],
       [ 1.89969252,  0.83444483],
       [-0.58723065, -1.97171753]])

In [5]:
y

array([1, 0, 0, 0, 0, 1, 1, 1, 1, 0])

In [6]:
# Convert the data to PyTorch tensors
X = torch.tensor(X, dtype=torch.float32)
y = torch.tensor(y, dtype=torch.long)

In [7]:
X

tensor([[ 1.0683, -0.9701],
        [-1.1402, -0.8388],
        [-2.8954,  1.9769],
        [-0.7206, -0.9606],
        [-1.9629, -0.9923],
        [-0.9382, -0.5430],
        [ 1.7273, -1.1858],
        [ 1.7774,  1.5116],
        [ 1.8997,  0.8344],
        [-0.5872, -1.9717]])

In [8]:
y

tensor([1, 0, 0, 0, 0, 1, 1, 1, 1, 0])

In [9]:
X

tensor([[ 1.0683, -0.9701],
        [-1.1402, -0.8388],
        [-2.8954,  1.9769],
        [-0.7206, -0.9606],
        [-1.9629, -0.9923],
        [-0.9382, -0.5430],
        [ 1.7273, -1.1858],
        [ 1.7774,  1.5116],
        [ 1.8997,  0.8344],
        [-0.5872, -1.9717]])

In [10]:
from torch.utils.data import Dataset, DataLoader

In [11]:
class CustomDataSet(Dataset):
    def __init__(self,features,labels):
        self.features=features
        self.labels=labels

    def __len__(self):
        return self.features.shape[0]

    def __getitem__(self,index):
        return self.features[index],self.labels[index]

In [12]:
dataset=CustomDataSet(X,y)

In [13]:
len(dataset)

10

In [14]:
dataset[2]

(tensor([-2.8954,  1.9769]), tensor(0))

In [15]:
dataset[9]

(tensor([-0.5872, -1.9717]), tensor(0))

In [16]:
dataloader=DataLoader(dataset,batch_size=2,shuffle=False)

In [17]:
dataloader

In [18]:
for batch_features, batch_labels in dataloader:

  print(batch_features)
  print(batch_labels)
  print("-"*50)

tensor([[ 1.0683, -0.9701],
        [-1.1402, -0.8388]])
tensor([1, 0])
--------------------------------------------------
tensor([[-2.8954,  1.9769],
        [-0.7206, -0.9606]])
tensor([0, 0])
--------------------------------------------------
tensor([[-1.9629, -0.9923],
        [-0.9382, -0.5430]])
tensor([0, 1])
--------------------------------------------------
tensor([[ 1.7273, -1.1858],
        [ 1.7774,  1.5116]])
tensor([1, 1])
--------------------------------------------------
tensor([[ 1.8997,  0.8344],
        [-0.5872, -1.9717]])
tensor([1, 0])
--------------------------------------------------
