In [1]:
import torch

In [2]:
print(torch.__version__)

2.6.0+cu124


In [3]:
if torch.cuda.is_available():
  print(torch.cuda.get_device_name(0))
  print('cuda')

Tesla T4
cuda


In [4]:
a = torch.empty(2,3)

In [5]:
a

tensor([[1.0043e+27, 4.4144e-41, 1.0043e+27],
        [4.4144e-41, 0.0000e+00, 0.0000e+00]])

In [6]:
type(a)

torch.Tensor

In [7]:
a.fill_(0)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [8]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [9]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [10]:
torch.rand(3,4)

tensor([[0.4285, 0.1614, 0.7686, 0.8747],
        [0.7874, 0.0432, 0.1684, 0.7953],
        [0.9552, 0.7998, 0.5535, 0.6765]])

In [11]:
torch.rand(3,4)

tensor([[0.5477, 0.3142, 0.2043, 0.7111],
        [0.3042, 0.4635, 0.9611, 0.3911],
        [0.0905, 0.1418, 0.8440, 0.7148]])

In [12]:
torch.rand(3,4)

tensor([[0.1353, 0.2824, 0.4389, 0.2448],
        [0.7112, 0.3088, 0.8824, 0.4531],
        [0.5054, 0.2267, 0.5471, 0.6558]])

In [13]:
torch.manual_seed(10)
torch.rand(3,4)


tensor([[0.4581, 0.4829, 0.3125, 0.6150],
        [0.2139, 0.4118, 0.6938, 0.9693],
        [0.6178, 0.3304, 0.5479, 0.4440]])

In [14]:
torch.manual_seed(10)
torch.rand(3,4)

tensor([[0.4581, 0.4829, 0.3125, 0.6150],
        [0.2139, 0.4118, 0.6938, 0.9693],
        [0.6178, 0.3304, 0.5479, 0.4440]])

In [15]:
torch.manual_seed(10)
torch.rand(3,4)

tensor([[0.4581, 0.4829, 0.3125, 0.6150],
        [0.2139, 0.4118, 0.6938, 0.9693],
        [0.6178, 0.3304, 0.5479, 0.4440]])

In [16]:
torch.manual_seed(11)
torch.rand(3,4)

tensor([[0.1490, 0.4866, 0.9857, 0.1684],
        [0.5839, 0.6936, 0.5831, 0.1284],
        [0.5721, 0.9248, 0.2693, 0.7825]])

In [17]:
torch.manual_seed(11)
torch.rand(3,4)

tensor([[0.1490, 0.4866, 0.9857, 0.1684],
        [0.5839, 0.6936, 0.5831, 0.1284],
        [0.5721, 0.9248, 0.2693, 0.7825]])

In [18]:
torch.tensor([[1,2,3],[3,4,5]])

tensor([[1, 2, 3],
        [3, 4, 5]])

In [19]:
torch.arange(10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
torch.arange(3,10)

tensor([3, 4, 5, 6, 7, 8, 9])

In [21]:
torch.arange(1,10,2)

tensor([1, 3, 5, 7, 9])

In [22]:
torch.linspace(0,1,30)

tensor([0.0000, 0.0345, 0.0690, 0.1034, 0.1379, 0.1724, 0.2069, 0.2414, 0.2759,
        0.3103, 0.3448, 0.3793, 0.4138, 0.4483, 0.4828, 0.5172, 0.5517, 0.5862,
        0.6207, 0.6552, 0.6897, 0.7241, 0.7586, 0.7931, 0.8276, 0.8621, 0.8966,
        0.9310, 0.9655, 1.0000])

In [23]:
torch.eye(5)

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [24]:
torch.full((3,3),5)

tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])

In [25]:
x = torch.tensor([[1,2,3],[3,4,5]])

In [26]:
x.shape

torch.Size([2, 3])

In [27]:
torch.empty_like(x)

tensor([[3616445622929465956, 6067529767688613173, 3978149841723863345],
        [6499875353475297838, 7309453675965983778, 8315168162784306286]])

In [28]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [29]:
torch.rand_like(x,dtype=torch.float32)

tensor([[0.2719, 0.4632, 0.7671],
        [0.5024, 0.1025, 0.7600]])

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


In [30]:
x

tensor([[1, 2, 3],
        [3, 4, 5]])

In [31]:
x+2

tensor([[3, 4, 5],
        [5, 6, 7]])

In [32]:
x-2

tensor([[-1,  0,  1],
        [ 1,  2,  3]])

In [33]:
x*3

tensor([[ 3,  6,  9],
        [ 9, 12, 15]])

In [34]:
x/3

tensor([[0.3333, 0.6667, 1.0000],
        [1.0000, 1.3333, 1.6667]])

In [35]:
c = torch.tensor([1, -2, 3, -4])

In [36]:
torch.abs(c)

tensor([1, 2, 3, 4])

In [37]:
torch.neg(c)

tensor([-1,  2, -3,  4])

In [38]:
d = torch.tensor([1.9, 2.3, 3.7, 4.4])

In [39]:
torch.round(d)

tensor([2., 2., 4., 4.])

In [40]:
torch.floor(d)

tensor([1., 2., 3., 4.])

In [41]:
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [42]:
e=torch.randint(size=(3,4),low=0,high=10,dtype=torch.float32)

In [43]:
e

tensor([[8., 1., 8., 2.],
        [8., 9., 2., 3.],
        [1., 7., 0., 1.]])

In [44]:
torch.sum(e)

tensor(50.)

In [45]:
torch.sum(e, dim=0)

tensor([17., 17., 10.,  6.])

In [46]:
torch.sum(e, dim=1)

tensor([19., 22.,  9.])

In [47]:
torch.mean(e, dim=1)

tensor([4.7500, 5.5000, 2.2500])

In [48]:
torch.mean(e)

tensor(4.1667)

In [49]:
torch.min(e)

tensor(0.)

In [50]:
torch.max(e)

tensor(9.)

argmax it is giving me index of highest value in matrix

In [51]:
torch.argmax(e)

tensor(5)

argmin it is giving me a index of minimum value in matrix

In [52]:
torch.argmin(e)

tensor(10)

In [53]:
e

tensor([[8., 1., 8., 2.],
        [8., 9., 2., 3.],
        [1., 7., 0., 1.]])

In [54]:
f = torch.randint(size=(2,3), low=0, high=10)
g = torch.randint(size=(3,2), low=0, high=10)

In [55]:
f

tensor([[5, 6, 0],
        [5, 3, 0]])

In [56]:
g

tensor([[3, 4],
        [0, 6],
        [9, 1]])

In [57]:
torch.matmul(f,g)

tensor([[15, 56],
        [15, 38]])

In [58]:
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

In [59]:
vector1

tensor([1, 2])

In [60]:
vector2

tensor([3, 4])

In [61]:
torch.dot(vector1,vector2)

tensor(11)

In [62]:
f

tensor([[5, 6, 0],
        [5, 3, 0]])

In [63]:
torch.transpose(f,0,1)

tensor([[5, 5],
        [6, 3],
        [0, 0]])

In [64]:
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)

In [65]:
h

tensor([[8., 7., 9.],
        [8., 5., 1.],
        [2., 5., 7.]])

In [66]:
torch.inverse(h)

tensor([[ 0.2273, -0.0303, -0.2879],
        [-0.4091,  0.2879,  0.4848],
        [ 0.2273, -0.1970, -0.1212]])

In [67]:
torch.log(h)

tensor([[2.0794, 1.9459, 2.1972],
        [2.0794, 1.6094, 0.0000],
        [0.6931, 1.6094, 1.9459]])

In [68]:
torch.exp(h)

tensor([[2.9810e+03, 1.0966e+03, 8.1031e+03],
        [2.9810e+03, 1.4841e+02, 2.7183e+00],
        [7.3891e+00, 1.4841e+02, 1.0966e+03]])

In [69]:
torch.softmax(h,0)

tensor([[4.9938e-01, 7.8699e-01, 8.8054e-01],
        [4.9938e-01, 1.0651e-01, 2.9539e-04],
        [1.2378e-03, 1.0651e-01, 1.1917e-01]])