### Word Embedding Techniques using Embedding Layer in Keras

In [1]:
### Libraries USed Tensorflow> 2.0  and keras

In [2]:
##tensorflow >2.0
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [4]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [5]:
### Vocabulary size   --- Total size of vocabulary
voc_size=10000

#### One Hot Representation

In [6]:
onehot_repr=[one_hot(words,voc_size)for words in sent]
print(onehot_repr)

[[4837, 9629, 7776, 5746], [4837, 9629, 7776, 9345], [4837, 2075, 7776, 8150], [9148, 6521, 3046, 8623, 7303], [9148, 6521, 3046, 8623, 8406], [1838, 4837, 8040, 7776, 8661], [4352, 2740, 213, 8623]]


### Word Embedding Represntation

In [7]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences   ### pad_sequence is helps to make the sentences in the same length
from tensorflow.keras.models import Sequential

In [8]:
import numpy as np

In [9]:
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)   # pre means if the sent_length is less than 8 at the begining it will add zeros to make length to 8
print(embedded_docs)

[[   0    0    0    0 4837 9629 7776 5746]
 [   0    0    0    0 4837 9629 7776 9345]
 [   0    0    0    0 4837 2075 7776 8150]
 [   0    0    0 9148 6521 3046 8623 7303]
 [   0    0    0 9148 6521 3046 8623 8406]
 [   0    0    0 1838 4837 8040 7776 8661]
 [   0    0    0    0 4352 2740  213 8623]]


In [10]:
dim=10


In [11]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [12]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding (Embedding)                │ ?                           │     0 (unbuilt) │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [13]:
print(model.predict(embedded_docs))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 234ms/step
[[[ 1.90305747e-02 -3.05138826e-02 -9.49988514e-03 -4.23103347e-02
   -4.05313261e-02  3.16098444e-02 -1.19294412e-02  4.85504903e-02
    4.92451303e-02  3.26676257e-02]
  [ 1.90305747e-02 -3.05138826e-02 -9.49988514e-03 -4.23103347e-02
   -4.05313261e-02  3.16098444e-02 -1.19294412e-02  4.85504903e-02
    4.92451303e-02  3.26676257e-02]
  [ 1.90305747e-02 -3.05138826e-02 -9.49988514e-03 -4.23103347e-02
   -4.05313261e-02  3.16098444e-02 -1.19294412e-02  4.85504903e-02
    4.92451303e-02  3.26676257e-02]
  [ 1.90305747e-02 -3.05138826e-02 -9.49988514e-03 -4.23103347e-02
   -4.05313261e-02  3.16098444e-02 -1.19294412e-02  4.85504903e-02
    4.92451303e-02  3.26676257e-02]
  [ 2.11917199e-02  4.20866162e-03 -1.78040974e-02 -7.42884725e-03
   -1.87195465e-03 -4.01851535e-02  4.52127345e-02  3.30691822e-02
   -1.98169947e-02 -2.82575842e-02]
  [ 3.44854109e-02 -1.56329982e-02 -3.37064043e-02 -9.21492651e-03
   -4.86071110e-02 -4.51142453e-02  3.124547

In [14]:
embedded_docs[0]  ## here the first value 0 is converted into vector values of 10 because we given dimensions as 10 so 10 values are created for each and every word

array([   0,    0,    0,    0, 4837, 9629, 7776, 5746], dtype=int32)

In [15]:
print(model.predict(embedded_docs)[0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 42ms/step
[[ 0.01903057 -0.03051388 -0.00949989 -0.04231033 -0.04053133  0.03160984
  -0.01192944  0.04855049  0.04924513  0.03266763]
 [ 0.01903057 -0.03051388 -0.00949989 -0.04231033 -0.04053133  0.03160984
  -0.01192944  0.04855049  0.04924513  0.03266763]
 [ 0.01903057 -0.03051388 -0.00949989 -0.04231033 -0.04053133  0.03160984
  -0.01192944  0.04855049  0.04924513  0.03266763]
 [ 0.01903057 -0.03051388 -0.00949989 -0.04231033 -0.04053133  0.03160984
  -0.01192944  0.04855049  0.04924513  0.03266763]
 [ 0.02119172  0.00420866 -0.0178041  -0.00742885 -0.00187195 -0.04018515
   0.04521273  0.03306918 -0.01981699 -0.02825758]
 [ 0.03448541 -0.015633   -0.0337064  -0.00921493 -0.04860711 -0.04511425
   0.03124547  0.02756231  0.02884481 -0.03846912]
 [-0.02793958  0.01041658  0.04595513 -0.04049442  0.02046547 -0.04817771
   0.00069497 -0.01322601  0.04608545  0.0444422 ]
 [ 0.03301976  0.01448948  0.03391883 -0.00761997  0.01223125  0.01038069
  -0.01306332